repos:
-   repo: local
    hooks:
    -   id: isort
        exclude: (poetry.lock|pyproject.toml|README.md|Dockerfile|.gitignore|.pre-commit-config.yaml||migrations/|core/database.py|db/database.py|Dockerfile|docker-compose.yml)
        name: isort
        entry: isort
        language: system
        types: [python]

    -   id: black
        exclude: (poetry.lock|pyproject.toml|README.md|Dockerfile|.gitignore|.pre-commit-config.yaml||migrations/|Dockerfile|docker-compose.yml|models.py)
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=110]

    -   id: flake8
        exclude: (poetry.lock|pyproject.toml|README.md|Dockerfile|.gitignore|.pre-commit-config.yaml||migrations/|Dockerfile|docker-compose.yml)
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--max-line-length=110"]
