"""empty message

Revision ID: 075b7f6dbe98
Revises: 188471b81175
Create Date: 2023-11-21 12:48:01.720118

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "075b7f6dbe98"
down_revision: Union[str, None] = "188471b81175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("note", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
